
inputs:
  - device: dht22
    name: Hygrometer_1
    pin: 10
    # pins:
    #   - 10
  - device: ads1115
    name: adc_1
    pin: 0
    poll_interval: 2
    channels:
      - name: water_level
        pin: 0
        # normalize: 26600

inps:
  - device:
      pin: 10
      name: test


triggers:
  # - name: trigger_1
  #   code: |
  #     if Hygrometer_1.temperature > 10:
  #       print("hygrotemp!: ",Hygrometer_1.temperature)
  #       rRelay_1 = True
  #       # Relay_1 = True if not Relay_1 else not Relay_1

  #     print("always print",Hygrometer_1)

  # - name: trigger_2
  #   code: print("trigger 2",rRelay_1)
  # - name: trigger_3
  #   code: relay_1.toggle()
  # - name: ads_trigger
  #   code: print("water level ",adc_1.water_level)
  - name: ads_test
    code: |
      print("water ",adc_1.water_level)
      if not relay_1.value and adc_1.water_level > 10000:
        relay_1.on()
      
      # is on
      if relay_1.value and adc_1.water_level < 3000:
        relay_1.off()
      print("relay state: ",relay_1.value)

  - name: humid
    code: |
      print("humid % ",Hygrometer_1.humidity)
      
      if Hygrometer_1.humidity > 70:
        relay_1.on()


outputs:
  - device: relay
    name: relay_1
    pin: 17
    active_high: False
    initial_value: False